provisioner:
  enabled: false
cilium:
  enabled: true
elk:
  enabled: true
prometheus:
  enabled: true

services:
  global:
    ipv6only: false

  vault:
    dev: true

  keycloak:
    externalUrl: "https://auth.proc.loc:31337"

  ingress:
    rootDomain: proc.loc
    tls:
      enabled: true
      secretName: solarweb
