bases:
  - environments.yaml
---

{{ readFile "hf-templates.yaml" }}

repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

releases:
- name: prometheus
  <<: *infra_default
  chart: prometheus-community/kube-prometheus-stack
  namespace: monitoring

