---
apiVersion: v1
kind: Service
metadata:
  name: fwd-dns
  namespace: kube-system
spec:
  type: NodePort
  ports:
    - port: 53
      nodePort: 30053
      protocol: UDP
  selector:
    k8s-app: kube-dns
---
apiVersion: v1
kind: Service
metadata:
  name: fwd-shumway
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8022
      nodePort: 30822
      protocol: TCP
  selector:
    selector.cilium.rbkmoney/release: shumway
---
apiVersion: v1
kind: Service
metadata:
  name: fwd-dominant
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8022
      nodePort: 31822
      protocol: TCP
  selector:
    selector.cilium.rbkmoney/release: dominant
---
apiVersion: v1
kind: Service
metadata:
  name: fwd-es
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 9200
      nodePort: 30200
      protocol: TCP
  selector:
    elasticsearch.k8s.elastic.co/cluster-name: rbkmoney
    common.k8s.elastic.co/type: elasticsearch
---
apiVersion: v1
kind: Service
metadata:
  name: fwd-postgres
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30432
      protocol: TCP
  selector:
    selector.cilium.rbkmoney/release: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: fwd-hellgate
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8022
      nodePort: 30723
      protocol: TCP
  selector:
    selector.cilium.rbkmoney/release: hellgate
---
apiVersion: v1
kind: Service
metadata:
  name: fwd-mocket-mpi
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8022
      nodePort: 30724
      protocol: TCP
  selector:
    selector.cilium.rbkmoney/release: proxy-mocketbank-mpi
apiVersion: v1
kind: Service
metadata:
  name: fwd-kibana
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 5601
      nodePort: 30601
      protocol: TCP
  selector:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: rbkmoney
