---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "default-holmes"
  namespace: {{ .Values.processingNamespace }}
specs:
  - endpointSelector:
      matchLabels:
        k8s:selector.cilium.rbkmoney/release: holmes
    egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: {{ .Values.processingNamespace | default .Release.Namespace }}
  - endpointSelector:
      matchLabels:
        k8s:io.kubernetes.pod.namespace: {{ .Values.processingNamespace | default .Release.Namespace }}
    ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:selector.cilium.rbkmoney/release: holmes