---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "vault-postgres"
  namespace: {{ .Values.processingNamespace | default .Release.Namespace }}
specs:
  - endpointSelector:
      matchLabels:
        k8s:selector.cilium.rbkmoney/release: vault
    egress:
    - toEndpoints:
      - matchLabels:
          k8s:selector.cilium.rbkmoney/release: postgres
      toPorts:
      - ports:
        - protocol: TCP
          port: "5432"
    - toEntities:
      - remote-node
      toPorts:
      - ports:
        - protocol: TCP
          port: "8443"
        - protocol: TCP
          port: "6443"
    - toEntities:
      - host
      toPorts:
      - ports:
        - protocol: TCP
          port: "8443"
        - protocol: TCP
          port: "6443"
  - endpointSelector:
      matchLabels:
        k8s:selector.cilium.rbkmoney/release: postgres
    ingress:
    - fromEndpoints:
      - matchLabels:
          k8s:selector.cilium.rbkmoney/release: vault
      toPorts:
      - ports:
        - protocol: TCP
          port: "5432"
  - endpointSelector:
      matchLabels:
        k8s:app.kubernetes.io/name: vault-agent-injector
    egress:
    - toEntities:
      - remote-node
      toPorts:
      - ports:
        - protocol: TCP
          port: "8443"
        - protocol: TCP
          port: "6443"
    - toEntities:
      - host
      toPorts:
      - ports:
        - protocol: TCP
          port: "8443"
        - protocol: TCP
          port: "6443"
